import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "../providers/NextAuth";
import Menu from "./components/organisms/Menu/Menu";
import { getServerSession } from "./api/auth/[...nextauth]/route";;
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div  className="grid grid-cols-[0.1fr_1fr] grid-rows-1">
            <Menu session={session} />
          {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
